### ISSUE TITLE
how to use in js (not template)?

### ISSUE THREAD

**Issue by thearabbit** [wollardj/timeago#1]
I use `tabular table` package for list view, so i want to custom the `date` field with timeago like:

``` javascript
TabularTable.Staff = new Tabular.Table({
    name: "StaffList",
    collection: Collection.Staff,
    columns: [
        {data: "name", title: "Name"},
        {data: "gender", title: "Gender"},
        {
            data: "startDate",
            title: "Start Date",
            render: function (val, type, doc) {
                return ...timeago...;
            }
        },
        {data: "address", title: "Address"},
........................
```

**Comment by wollardj** [comment]
This package is just a very simple wrapper around just a few of the features in momentjs that was meant to serve a few specific, template-based scenarios I had. If you want to use it outside of a template, I'd suggest not using this package and instead just using momentjs by itself.

See [momentjs.com](http://momentjs.com/) for the full documentation
See [wollardj:timeago.coffee](https://github.com/wollardj/timeago/blob/master/wollardj:timeago.coffee) for the way this package uses momentjs

**Comment by thearabbit** [comment]
I try to use `momentjs`, but it don't `reactive/realtime` udpate.

**Comment by wollardj** [comment]
The only reason the timeago package has reactive/realtime updates is because it relies on Templates. In the title of this issue you explicitly mention wanting to use it outside of Templates, so this package just isn't going to suit your needs. You'd need to implement [something like this](https://github.com/wollardj/timeago/blob/master/wollardj:timeago.coffee#L43-L45), but you'd need to manually keep track of the DOM elements that need to be updated since they wouldn't be tied to a Template instance.
